// Comprehensive bank design specifications matching original bank login pages
import { BankDesign } from './banks';

export const BANK_DESIGNS: Record<string, BankDesign> = {
  // Al Rajhi Bank - مصرف الراجحي
  alrajhi_bank: {
    primaryColor: '#006C35',
    secondaryColor: '#00A650',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#F8F9FA',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    inputStyle: 'modern',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  // Al Ahli Bank - البنك الأهلي التجاري
  alahli_bank: {
    primaryColor: '#00843D',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F7FA',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E5E5E5',
    fontFamily: 'Almarai, sans-serif',
    fontFamilyArabic: 'Almarai',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '460px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'prominent',
    showDecorativeElements: false,
  },

  // Riyad Bank - بنك الرياض
  riyad_bank: {
    primaryColor: '#0066B2',
    secondaryColor: '#004B87',
    backgroundColor: '#F5F7FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'split',
    containerMaxWidth: '1200px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '6px',
    inputStyle: 'classic',
    inputRadius: '6px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  // Samba Financial Group - مجموعة سامبا المالية
  samba_bank: {
    primaryColor: '#E31E24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'IBM Plex Sans Arabic, sans-serif',
    fontFamilyArabic: 'IBM Plex Sans Arabic',
    fontWeight: '500',
    layoutType: 'centered',
    containerMaxWidth: '450px',
    cardStyle: 'outlined',
    borderRadius: '12px',
    buttonStyle: 'solid',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'minimal',
    showDecorativeElements: false,
  },

  // Saudi Investment Bank - البنك السعودي للاستثمار
  saudi_investment_bank: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '8px',
    inputStyle: 'classic',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  // Arab National Bank - البنك العربي الوطني
  arab_national_bank: {
    primaryColor: '#00A551',
    secondaryColor: '#00843D',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#F8F9FA',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '460px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  // Emirates NBD
  emirates_nbd: {
    primaryColor: '#D50032',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    layoutType: 'full-width',
    containerMaxWidth: '500px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'prominent',
    showDecorativeElements: true,
  },

  // Abu Dhabi Commercial Bank
  adcb: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F5F7FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Arial, sans-serif',
    fontFamilyArabic: 'Arial',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '8px',
    inputStyle: 'classic',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  // First Abu Dhabi Bank
  fab: {
    primaryColor: '#000000',
    secondaryColor: '#333333',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#000000',
    textSecondaryColor: '#666666',
    borderColor: '#CCCCCC',
    fontFamily: 'Helvetica Neue, Arial, sans-serif',
    fontFamilyArabic: 'Arial',
    fontWeight: '600',
    layoutType: 'centered',
    containerMaxWidth: '450px',
    cardStyle: 'minimal',
    borderRadius: '0px',
    buttonStyle: 'solid',
    buttonRadius: '0px',
    inputStyle: 'minimal',
    inputRadius: '0px',
    headerStyle: 'minimal',
    showDecorativeElements: false,
  },

  // Dubai Islamic Bank
  dib: {
    primaryColor: '#00923F',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  // Qatar National Bank
  qnb: {
    primaryColor: '#6E1D3E',
    secondaryColor: '#8E1838',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#F8F9FA',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'QNB Font, Arial, sans-serif',
    fontFamilyArabic: 'Arial',
    fontWeight: '500',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  // Add more banks with similar patterns - using defaults for now
  // Saudi banks
  saudi_fransi_bank: {
    primaryColor: '#ED1C24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '460px',
    cardStyle: 'outlined',
    borderRadius: '10px',
    buttonStyle: 'solid',
    buttonRadius: '10px',
    inputStyle: 'classic',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  alinma_bank: {
    primaryColor: '#00A650',
    secondaryColor: '#00843D',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#333333',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    inputStyle: 'modern',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  albilad_bank: {
    primaryColor: '#1C4587',
    secondaryColor: '#004B87',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'classic',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '6px',
    inputStyle: 'classic',
    inputRadius: '6px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  aljazira_bank: {
    primaryColor: '#005EB8',
    secondaryColor: '#0066B2',
    backgroundColor: '#F5F7FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  // UAE banks
  mashreq_bank: {
    primaryColor: '#E31E24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'solid',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  cbd: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Arial, sans-serif',
    fontFamilyArabic: 'Arial',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '8px',
    inputStyle: 'classic',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  rakbank: {
    primaryColor: '#E31E24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'solid',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  ajman_bank: {
    primaryColor: '#00A651',
    secondaryColor: '#00843D',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  // Kuwait banks
  nbk: {
    primaryColor: '#005EB8',
    secondaryColor: '#004B87',
    backgroundColor: '#F5F7FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'classic',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '6px',
    inputStyle: 'classic',
    inputRadius: '6px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  gulf_bank: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'classic',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '6px',
    inputStyle: 'classic',
    inputRadius: '6px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  cbk: {
    primaryColor: '#00A651',
    secondaryColor: '#00843D',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    inputStyle: 'modern',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  burgan_bank: {
    primaryColor: '#E31E24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  ahli_united_bank: {
    primaryColor: '#00843D',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#333333',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    inputStyle: 'modern',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  kfh: {
    primaryColor: '#00923F',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  boubyan_bank: {
    primaryColor: '#0066B2',
    secondaryColor: '#004B87',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  // Qatar banks
  cbq: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F5F7FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'classic',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '8px',
    inputStyle: 'classic',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  doha_bank: {
    primaryColor: '#E31E24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'solid',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  qib: {
    primaryColor: '#00923F',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  masraf_alrayan: {
    primaryColor: '#00A651',
    secondaryColor: '#00843D',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  ahlibank: {
    primaryColor: '#00843D',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#333333',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    inputStyle: 'modern',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  // Oman banks
  bank_muscat: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'classic',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '6px',
    inputStyle: 'classic',
    inputRadius: '6px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  national_bank_oman: {
    primaryColor: '#00A651',
    secondaryColor: '#00843D',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  bank_dhofar: {
    primaryColor: '#E31E24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  ahli_bank_oman: {
    primaryColor: '#00843D',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#333333',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    inputStyle: 'modern',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  nizwa_bank: {
    primaryColor: '#00923F',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  sohar_international: {
    primaryColor: '#0066B2',
    secondaryColor: '#004B87',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  // Bahrain banks
  nbb: {
    primaryColor: '#E31E24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  bbk: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'classic',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '6px',
    inputStyle: 'classic',
    inputRadius: '6px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  ahli_united_bahrain: {
    primaryColor: '#00843D',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#333333',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    inputStyle: 'modern',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  bisb: {
    primaryColor: '#00923F',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  ithmaar_bank: {
    primaryColor: '#00A651',
    secondaryColor: '#00843D',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  khaleeji_bank: {
    primaryColor: '#0066B2',
    secondaryColor: '#004B87',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },
};

// Get design for a bank by ID
export const getBankDesign = (bankId: string): BankDesign | undefined => {
  return BANK_DESIGNS[bankId];
};

// Get default design if bank not found
export const getDefaultBankDesign = (): BankDesign => ({
  primaryColor: '#0EA5E9',
  secondaryColor: '#06B6D4',
  backgroundColor: '#FFFFFF',
  surfaceColor: '#F8F9FA',
  textColor: '#1A1A1A',
  textSecondaryColor: '#666666',
  borderColor: '#E0E0E0',
  fontFamily: 'Tajawal, sans-serif',
  fontFamilyArabic: 'Tajawal',
  fontWeight: '400',
  layoutType: 'centered',
  containerMaxWidth: '480px',
  cardStyle: 'elevated',
  borderRadius: '12px',
  buttonStyle: 'gradient',
  buttonRadius: '8px',
  inputStyle: 'modern',
  inputRadius: '8px',
  headerStyle: 'standard',
  showDecorativeElements: false,
});
